---
- name: Install MariaDB package key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

- name: Add MariaDB source 
  apt_repository: repo='deb [arch=amd64,i386,ppc64el] http://mirror.klaus-uwe.me/mariadb/repo/10.1/ubuntu trusty main' state=present

- name: Install MariaDB package
  apt: name={{item}} state=latest
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Start MariaDB Service
  service: name=mysql state=started enabled=yes

# localhost needs to be the last item for idempotency
- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Delete anonymous MySQL server user for $server_hostname
  action: mysql_user user="" host="{{ server_hostname }}" state="absent"

- name: Delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"

- name: Remove the MySQL test database
  action: mysql_db db=test state=absent

- name: Download MySQL Tuner
  get_url: url=https://raw.githubusercontent.com/major/MySQLTuner-perl/master/mysqltuner.pl dest=/home/{{ remote_user }}
