---
- name: Set newrelic_loaded_os_family
  set_fact:
    newrelic_loaded_os_family: "{{ ansible_os_family }}"

- name: Add New Relic repo key
  apt_key:
    url: https://download.newrelic.com/548C16BF.gpg
    id: 548C16BF
    state: present

- name: Add New Relic repository
  copy:
    content: "deb http://apt.newrelic.com/debian/ newrelic non-free"
    dest: /etc/apt/sources.list.d/newrelic.list
    owner: root
    group: root
    mode: 0644
  register: newrelic_repo

- name: apt-get update
  apt:
    update_cache: yes
  when: newrelic_repo.changed

- name: Install New Relic Sysmond
  apt:
    pkg: newrelic-sysmond
    update_cache: yes
    cache_valid_time: 86400
    state: latest
  notify:
    - restart new relic


- name: Configure New Relic Sysmond
  template:
    src: nrsysmond.cfg
    dest: /etc/newrelic/nrsysmond.cfg
    group: newrelic
    owner: root
    mode: 0640
  notify:
    - restart new relic

- name: Ensure New Relic Sysmond is started and enabled
  service:
    name: newrelic-sysmond
    state: started
    enabled: yes

# PHP time

- name: Install New Relic PHP Agent
  apt:
    pkg: newrelic-php5
    state: latest
  notify:
    - run new relic installer

- name: Configure New Relic PHP Agent
  template:
    src: newrelic.ini
    dest: "/etc/php/7.0/fpm/conf.d/newrelic.ini"
    group: root
    owner: root
    mode: 0640
  notify:
    - run new relic installer

